import Hola from '@/app/componestes/Hola'
import Navbar from '@/app/componestes/Navbar'
import './globals.css'
import BuscarPage from './buscar/page'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
