import { Inter } from "next/font/google";
import './globals.css'
import MenuBarra from "@/components/MenuBarra";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
         <MenuBarra/>
        {children}
      </body>
    </html>
  )
}
